version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt

  pre_build:
    commands:
      - echo Starting pre-build step

  build:
    commands:
      - echo Running unit tests with pytest...
      - python -m pytest --junitxml=reports/results.xml --tb=short

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - "**/*"
  base-directory: .

reports:
  pytest_reports:
    files:
      - "reports/results.xml"
    discard-paths: yes
